### PR TITLE
🐛 Fix regex characters not being escaped in template destructure patterns

### LINKED ISSUE #86: 🐛 Template destructure patterns should escape strings with RegExp characters in them.
Consider the following code:
```
pub let main = {
    let url = "https://www.test.com"
    ret where url
        is `${protocol}://www.${domain}.${tld}` =>
            console.log [ protocol, domain, tld ]
}
```
We would expect this to log `[ "https", "test", "com" ]`, but if you run it and inspect the output you might be surprised to see `[ "https", "test.co", "" ]`. 

This is because the template pattern has two periods (`.`) in it that altered the meaning of the compiled regular expression slightly. To get the intended behaviour, one currently has to write:
```
pub let main = {
    let url = "https://www.test.com"
    ret where url
        is `${protocol}://www\\\\.${domain}\\\\.${tld}` =>
            console.log [ protocol, domain, tld ]
}
```
to manually escape those characters. This is obviously no good, and leaks implementation details in a place that is really not acceptable. We should automatically escape the string literal portions of the template pattern when emitting JavaScript.

---

MDN provides a non-exhaustive but good-enough escaping function in JavaScript. Maybe we can repurpose that:
```js
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

### PR DESCRIPTION
**Pull request by Alpvax**
Fixes #86 

Currently there is an issue with attempting to escape `${...` in template strings, so that cannot be tested.

### CODE REVIEW

**Comment by hayleigh-dot-dev** [comment]
Yeah excellent! Tested it against:
```
let url = "http://www.test.com"
let foo = where url
  is `${protocol}://www.${domain}.com` => 
    [ protocol, domain ]

run console.log foo
```
And it logs `[ "http", "test" ]` as expected, nice!

**Comment by Alpvax** [comment]
That would pass anyway (`.` matches `.`).
You should probably test it against something like `http://wwwftest.com` (should fail)

**Comment by hayleigh-dot-dev** [comment]
I'm just gonna assume you were rigorous enough and blame you if it's still broken 😎.

**Comment by Alpvax** [comment]
Haha, I'll just claim "Not a bug, it's a feature".
If it's broken (which it shouldn't be) I'll fix it when I fix string escapes.

**Pull request merged**
